<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class HomestaySeeder extends Seeder
{
    public function run(): void
    {
        $owners = [
            ['name' => 'Ahmad Razak bin Ibrahim', 'email' => 'ahmad.razak@homestay.my', 'role' => 3, 'password' => Hash::make('password')],
            ['name' => 'Siti Nurhaliza binti Hassan', 'email' => 'siti.nurhaliza@homestay.my', 'role' => 3, 'password' => Hash::make('password')],
            ['name' => 'Lim Wei Jie', 'email' => 'lim.weijie@homestay.my', 'role' => 3, 'password' => Hash::make('password')],
            ['name' => 'Rajesh Kumar a/l Muthu', 'email' => 'rajesh.kumar@homestay.my', 'role' => 3, 'password' => Hash::make('password')],
            ['name' => 'Nur Aisyah binti Abdullah', 'email' => 'nur.aisyah@homestay.my', 'role' => 3, 'password' => Hash::make('password')],
        ];

        $ownerIds = [];
        foreach ($owners as $owner) {
            $ownerIds[] = DB::table('users')->insertGetId($owner);
        }

        $allOwnerIds = array_merge([2], $ownerIds);

        $homestays = [
            [
                'owner_id' => $allOwnerIds[0],
                'homestay_name' => 'Bayu Pantai Retreat',
                'description' => 'A charming beachfront homestay in Langkawi with stunning sea views. Perfect for families seeking a relaxing island getaway with easy access to Pantai Cenang attractions and water sports. Features a private balcony overlooking the Andaman Sea.',
                'address' => 'Lot 45, Pantai Cenang Road, Mukim Padang Matsirat',
                'street' => 'Pantai Cenang Road',
                'city' => 'Langkawi',
                'zipcode' => '07000',
                'state' => 'Kedah',
                'latitude' => 6.3024,
                'longitude' => 99.7865,
                'base_price' => 280.00,
                'max_guest' => 8,
                'status' => 'active',
            ],
            [
                'owner_id' => $allOwnerIds[1],
                'homestay_name' => 'Tropika Gemilang Villa',
                'description' => 'Modern tropical villa nestled in the heart of Cheras, Kuala Lumpur. Spacious living areas with contemporary design, fully equipped kitchen, and a private garden. Ideal for business travelers and families wanting city convenience with resort-like comfort.',
                'address' => 'No. 12, Jalan Tropika Gemilang 3, Taman Tropika Gemilang',
                'street' => 'Jalan Tropika Gemilang 3',
                'city' => 'Cheras',
                'zipcode' => '43200',
                'state' => 'WP Kuala Lumpur',
                'latitude' => 3.1087,
                'longitude' => 101.7278,
                'base_price' => 350.00,
                'max_guest' => 10,
                'status' => 'active',
            ],
            [
                'owner_id' => $allOwnerIds[2],
                'homestay_name' => 'Desa Cermin Danau',
                'description' => 'A serene lakeside homestay near Tasik Kenyir, Terengganu. Wake up to misty lake views and enjoy kayaking, fishing, and jungle trekking. Traditional Malay architecture blended with modern comforts. Perfect for nature lovers and adventure seekers.',
                'address' => 'Lot 78, Kampung Desa Cermin, Hulu Terengganu',
                'street' => 'Kampung Desa Cermin',
                'city' => 'Kenyir',
                'zipcode' => '21800',
                'state' => 'Terengganu',
                'latitude' => 5.0250,
                'longitude' => 102.6380,
                'base_price' => 180.00,
                'max_guest' => 6,
                'status' => 'active',
            ],
            [
                'owner_id' => $allOwnerIds[3],
                'homestay_name' => 'Puncak Bintang Cottage',
                'description' => 'Cozy hilltop cottage in Genting Highlands offering cool mountain breezes and panoramic views. Just minutes from Skytropolis Funland and cable car station. Features a cozy fireplace lounge and outdoor BBQ area. Great for weekend escapes from city heat.',
                'address' => 'No. 5, Jalan Puncak Bintang, Genting Highlands',
                'street' => 'Jalan Puncak Bintang',
                'city' => 'Genting Highlands',
                'zipcode' => '69000',
                'state' => 'Pahang',
                'latitude' => 3.4250,
                'longitude' => 101.7880,
                'base_price' => 420.00,
                'max_guest' => 8,
                'status' => 'active',
            ],
            [
                'owner_id' => $allOwnerIds[4],
                'homestay_name' => 'Rumah Seri Melaka',
                'description' => 'Heritage-style homestay in the heart of Melaka UNESCO zone. Walking distance to Jonker Walk, A Famosa, and St Paul Church. Authentic Peranakan-inspired interiors with antique furnishings. Experience Melaka rich history while staying in comfortable modernized quarters.',
                'address' => 'No. 23, Jalan Hang Jebat, Bandar Hilir',
                'street' => 'Jalan Hang Jebat',
                'city' => 'Melaka City',
                'zipcode' => '75000',
                'state' => 'Melaka',
                'latitude' => 2.1960,
                'longitude' => 102.2490,
                'base_price' => 220.00,
                'max_guest' => 6,
                'status' => 'active',
            ],
            [
                'owner_id' => $allOwnerIds[0],
                'homestay_name' => 'Sutera Tambun Springs',
                'description' => 'Hot spring retreat in Ipoh surrounded by limestone hills and lush greenery. Adjacent to Lost World of Tambun theme park. Features natural hot spring pools, spacious family rooms, and adventure activity packages. Ideal for family fun and wellness retreats.',
                'address' => 'Lot 33, Jalan Tambun, Sunway City Ipoh',
                'street' => 'Jalan Tambun',
                'city' => 'Ipoh',
                'zipcode' => '31100',
                'state' => 'Perak',
                'latitude' => 4.5830,
                'longitude' => 101.1100,
                'base_price' => 260.00,
                'max_guest' => 8,
                'status' => 'active',
            ],
            [
                'owner_id' => $allOwnerIds[1],
                'homestay_name' => 'Sri Kinabalu Lodge',
                'description' => 'Mountain lodge at the foothills of Mount Kinabalu in Sabah. Gateway to Kinabalu Park and Poring Hot Springs. Rustic yet comfortable rooms with mountain views, on-site restaurant serving local Kadazan cuisine. Perfect for climbers and eco-tourists.',
                'address' => 'Lot 15, Kampung Kundasang, Ranau',
                'street' => 'Kampung Kundasang',
                'city' => 'Ranau',
                'zipcode' => '89500',
                'state' => 'Sabah',
                'latitude' => 5.9830,
                'longitude' => 116.5830,
                'base_price' => 150.00,
                'max_guest' => 5,
                'status' => 'active',
            ],
            [
                'owner_id' => $allOwnerIds[2],
                'homestay_name' => 'Harmony Bay Penang',
                'description' => 'Stylish sea-facing apartment in Batu Ferringhi, Penang. Direct beach access with water sport facilities nearby. Modern interior design with panoramic sea-facing windows. Close to Penang night market and hawker centres. Ideal for beach lovers and food enthusiasts.',
                'address' => 'Block A-12-03, Batu Ferringhi Heights, Jalan Batu Ferringhi',
                'street' => 'Jalan Batu Ferringhi',
                'city' => 'Batu Ferringhi',
                'zipcode' => '11100',
                'state' => 'Pulau Pinang',
                'latitude' => 5.4740,
                'longitude' => 100.2730,
                'base_price' => 320.00,
                'max_guest' => 7,
                'status' => 'active',
            ],
            [
                'owner_id' => $allOwnerIds[3],
                'homestay_name' => 'Laman Rimbun Pahang',
                'description' => 'Eco-friendly riverside homestay in Kuala Tahan, gateway to Taman Negara National Park. Wake up to rainforest sounds and Tembeling River views. Guided jungle treks, canopy walks, and river cruises available. Authentic kampung experience with eco-conscious amenities.',
                'address' => 'Lot 56, Kampung Kuala Tahan, Jerantut',
                'street' => 'Kampung Kuala Tahan',
                'city' => 'Kuala Tahan',
                'zipcode' => '27000',
                'state' => 'Pahang',
                'latitude' => 4.3830,
                'longitude' => 102.3830,
                'base_price' => 140.00,
                'max_guest' => 5,
                'status' => 'active',
            ],
            [
                'owner_id' => $allOwnerIds[4],
                'homestay_name' => 'Kota Seri Negeri Home',
                'description' => 'Comfortable suburban homestay in Seremban, Negeri Sembilan. Close to Palm Mall, Terminal 1 shopping, and Seremban cultural attractions. Minangkabau-inspired architecture with modern amenities. Great base for exploring Negeri Sembilan heritage sites and culinary trails.',
                'address' => 'No. 8, Jalan Kota Seri 2, Taman Kota Seri',
                'street' => 'Jalan Kota Seri 2',
                'city' => 'Seremban',
                'zipcode' => '70450',
                'state' => 'Negeri Sembilan',
                'latitude' => 2.7270,
                'longitude' => 101.9380,
                'base_price' => 160.00,
                'max_guest' => 6,
                'status' => 'active',
            ],
            [
                'owner_id' => $allOwnerIds[0],
                'homestay_name' => 'Senandung Johor Villa',
                'description' => 'Luxury villa in Desaru Coast, Johor with private pool and beach access. Part of the premium Desaru Coast resort area with water park and golf course nearby. Elegant interiors, outdoor dining terrace, and full kitchen. Suitable for family reunions and celebratory stays.',
                'address' => 'Villa 7, Desaru Coast Residences, Jalan Desaru',
                'street' => 'Jalan Desaru',
                'city' => 'Desaru',
                'zipcode' => '81930',
                'state' => 'Johor',
                'latitude' => 1.5580,
                'longitude' => 104.2730,
                'base_price' => 550.00,
                'max_guest' => 12,
                'status' => 'active',
            ],
            [
                'owner_id' => $allOwnerIds[1],
                'homestay_name' => 'Cahaya Borneo Stay',
                'description' => 'Riverside longhouse-inspired homestay in Kuching, Sarawak. Overlooking the Sarawak River with sunset views from the rooftop terrace. Walking distance to Kuching Waterfront, Sarawak Cultural Village, and Bako National Park departure point. Experience authentic Sarawak culture and cuisine.',
                'address' => 'No. 10, Jalan Cahaya Borneo, Kampung Boyan',
                'street' => 'Jalan Cahaya Borneo',
                'city' => 'Kuching',
                'zipcode' => '93000',
                'state' => 'Sarawak',
                'latitude' => 1.5580,
                'longitude' => 110.3580,
                'base_price' => 190.00,
                'max_guest' => 6,
                'status' => 'active',
            ],
            [
                'owner_id' => $allOwnerIds[2],
                'homestay_name' => 'Seri Kelantan Kampung',
                'description' => 'Traditional Malay kampung house in Kota Bharu, Kelantan. Experience authentic Kelantanese culture with nearby attractions like Handicraft Village, Istana Jahar, and Siti Khadijah Market. Home-cooked local breakfast included. Handicraft workshops available on request.',
                'address' => 'Lot 22, Kampung Seri Kelantan, Jalan Sultanah Zainab',
                'street' => 'Jalan Sultanah Zainab',
                'city' => 'Kota Bharu',
                'zipcode' => '15200',
                'state' => 'Kelantan',
                'latitude' => 6.1380,
                'longitude' => 102.2490,
                'base_price' => 120.00,
                'max_guest' => 4,
                'status' => 'active',
            ],
            [
                'owner_id' => $allOwnerIds[3],
                'homestay_name' => 'Gemilang Putrajaya Suite',
                'description' => 'Premium serviced suite in Putrajaya overlooking the iconic Putra Mosque and lake. Modern furnishings with smart home features. Walking distance to IOI City Mall and Putrajaya attractions including Botanical Garden and Millennium Monument. Perfect for government visitors and tourists.',
                'address' => 'Unit 18-08, Gemilang Residence, Jalan Presint 16',
                'street' => 'Jalan Presint 16',
                'city' => 'Putrajaya',
                'zipcode' => '62100',
                'state' => 'WP Putrajaya',
                'latitude' => 2.9270,
                'longitude' => 101.6880,
                'base_price' => 300.00,
                'max_guest' => 4,
                'status' => 'active',
            ],
            [
                'owner_id' => $allOwnerIds[4],
                'homestay_name' => 'Rimba Cameron Hideaway',
                'description' => 'Cozy wooden cabin in Cameron Highlands surrounded by tea plantations and strawberry farms. Fresh mountain air, fireplace lounge, and outdoor BBQ deck. Close to Boh Tea Estate, Mossy Forest trail, and Kea Farm market. A perfect cool-weather retreat from tropical lowlands.',
                'address' => 'Cabin 4, Jalan Rimba, Tanah Rata',
                'street' => 'Jalan Rimba',
                'city' => 'Tanah Rata',
                'zipcode' => '39000',
                'state' => 'Pahang',
                'latitude' => 4.4730,
                'longitude' => 101.3830,
                'base_price' => 200.00,
                'max_guest' => 6,
                'status' => 'active',
            ],
            [
                'owner_id' => $allOwnerIds[0],
                'homestay_name' => 'Pantai Timur Resort',
                'description' => 'Beachfront resort-style homestay in Cherating, Pahang. Direct access to Cherating Beach, surfing spot, and turtle sanctuary. Wooden chalet design with open-air living areas. Close to Cherating Cultural Village and Club Med. Ideal for surfers and beach holidaymakers.',
                'address' => 'Chalet 9, Pantai Cherating, Balok',
                'street' => 'Pantai Cherating',
                'city' => 'Cherating',
                'zipcode' => '26080',
                'state' => 'Pahang',
                'latitude' => 4.1580,
                'longitude' => 103.3830,
                'base_price' => 170.00,
                'max_guest' => 6,
                'status' => 'active',
            ],
            [
                'owner_id' => $allOwnerIds[1],
                'homestay_name' => 'Mutiara Perlis Inn',
                'description' => 'Charming inn in Kangar, Perlis near the Thai border. Gateway to Perlis State Park and Gua Kelam limestone cave. Traditional Malay-style rooms with modern bathrooms. Local Perlis cuisine breakfast featuring ikan bakar and laksa Perlis. Affordable and authentic northern Malaysia experience.',
                'address' => 'No. 15, Jalan Mutiara, Taman Mutiara Kangar',
                'street' => 'Jalan Mutiara',
                'city' => 'Kangar',
                'zipcode' => '01000',
                'state' => 'Perlis',
                'latitude' => 6.4380,
                'longitude' => 100.1880,
                'base_price' => 100.00,
                'max_guest' => 4,
                'status' => 'active',
            ],
            [
                'owner_id' => $allOwnerIds[2],
                'homestay_name' => 'Sekinchan Padi View',
                'description' => 'Rice paddy field homestay in Sekinchan, Selangor. Stunning views of endless green paddy fields and coastal breeze. Featured in popular TV dramas. Seasonal paddy planting and harvesting experiences available. Nearby seafood restaurants at Pantai Redang. A unique agritourism stay.',
                'address' => 'Lot 34, Kampung Sekinchan, Jalan Sekinchan',
                'street' => 'Jalan Sekinchan',
                'city' => 'Sekinchan',
                'zipcode' => '45400',
                'state' => 'Selangor',
                'latitude' => 3.5580,
                'longitude' => 101.1580,
                'base_price' => 130.00,
                'max_guest' => 5,
                'status' => 'active',
            ],
            [
                'owner_id' => $allOwnerIds[3],
                'homestay_name' => 'Labuan Island Stay',
                'description' => 'Island homestay in Labuan with duty-free shopping proximity. Sea-facing balcony with views of Labuan harbour. Close to Labuan International Sea Sport Complex and World War II memorial sites. Island hopping packages to Layang-Layang and Kuraman islands available. Perfect for divers and shoppers.',
                'address' => 'Unit 5-02, Labuan Heights, Jalan Merdeka',
                'street' => 'Jalan Merdeka',
                'city' => 'Labuan',
                'zipcode' => '87000',
                'state' => 'WP Labuan',
                'latitude' => 5.3080,
                'longitude' => 115.2480,
                'base_price' => 140.00,
                'max_guest' => 4,
                'status' => 'active',
            ],
            [
                'owner_id' => $allOwnerIds[4],
                'homestay_name' => 'Puteri Gunung Ledang Rest',
                'description' => 'Nature retreat near Mount Ledang in Tangkak, Johor. Gateway to Gunung Ledang National Park with hiking trails, cascading waterfall, and natural pools. Rustic timber cabins with modern bathrooms and outdoor dining area. Popular with hikers and eco-tourists seeking authentic jungle proximity.',
                'address' => 'Cabin 3, Jalan Puteri, Kampung Asahan, Tangkak',
                'street' => 'Jalan Puteri',
                'city' => 'Tangkak',
                'zipcode' => '84900',
                'state' => 'Johor',
                'latitude' => 2.2780,
                'longitude' => 102.5880,
                'base_price' => 160.00,
                'max_guest' => 5,
                'status' => 'active',
            ],
        ];

        $amenityPool = [3, 4, 5, 6, 8, 9, 10, 11];

        foreach ($homestays as $hs) {
            $homestayId = DB::table('homestays')->insertGetId($hs);

            $numImages = rand(3, 5);
            for ($i = 1; $i <= $numImages; $i++) {
                $ext = $i === 1 ? 'png' : 'jpg';
                DB::table('homestay_images')->insert([
                    'homestay_id' => $homestayId,
                    'image_path' => "assets/images/ownerHomestay/{$homestayId}/img-{$i}.{$ext}",
                    'image_type' => 'gallery',
                    'metadata' => null,
                ]);
            }

            $numAmenities = rand(3, 6);
            $selectedAmenities = array_rand(array_flip($amenityPool), $numAmenities);
            foreach ($selectedAmenities as $amenityId) {
                DB::table('homestay_amenities')->insert([
                    'homestay_id' => $homestayId,
                    'amenity_id' => $amenityId,
                ]);
            }
        }

        $this->command->info('20 homestays seeded successfully across Malaysia!');
    }
}
