<?php

namespace App\Jobs;

use App\Models\RoomScan;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Queue\Queueable;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Storage;
use Symfony\Component\Process\Process;

class ProcessRoomScan implements ShouldQueue
{
    use Queueable;

    public int $tries = 3;
    public int $backoff = 10;

    public function __construct(public int $roomScanId)
    {
    }

    public function handle(): void
    {
        $scan = RoomScan::findOrFail($this->roomScanId);

        if (($scan->metadata['scan_type'] ?? null) === 'panorama_360') {
            $scan->update([
                'status' => 'completed',
                'error_message' => null,
                'processing_log' => 'Single 360 panorama uploaded. No COLMAP reconstruction was needed for this room viewer.',
                'started_at' => $scan->started_at ?? now(),
                'completed_at' => now(),
            ]);

            return;
        }

        $basePath = $this->resolveScanBasePath($scan->folder);
        $imagesPath = "{$basePath}/images";
        $databasePath = "{$basePath}/database.db";
        $sparsePath = "{$basePath}/sparse";
        $textOutputPath = "{$basePath}/output/txt";
        $publicDisk = config('roomscan.public_disk', 'public');
        $publicOutputPath = "scans/{$scan->folder}/point-cloud.json";

        File::ensureDirectoryExists($imagesPath);
        File::ensureDirectoryExists($sparsePath);
        File::ensureDirectoryExists($textOutputPath);

        $scan->update([
            'status' => 'processing',
            'started_at' => now(),
            'completed_at' => null,
            'error_message' => null,
            'processing_log' => null,
        ]);

        $log = [];

        try {
            $colmap = config('roomscan.colmap_binary');

            if (! $colmap) {
                throw new \RuntimeException('COLMAP binary path is not configured. Set COLMAP_BIN in your environment first.');
            }

            $this->runProcess([
                $colmap,
                'feature_extractor',
                '--database_path', $databasePath,
                '--image_path', $imagesPath,
                '--FeatureExtraction.use_gpu', config('roomscan.use_gpu', false) ? '1' : '0',
            ], $log);

            $this->runProcess([
                $colmap,
                'exhaustive_matcher',
                '--database_path', $databasePath,
                '--FeatureMatching.use_gpu', config('roomscan.use_gpu', false) ? '1' : '0',
            ], $log);

            $this->runProcess([
                $colmap,
                'mapper',
                '--database_path', $databasePath,
                '--image_path', $imagesPath,
                '--output_path', $sparsePath,
            ], $log);

            $firstModelPath = "{$sparsePath}/0";

            if (! File::isDirectory($firstModelPath)) {
                throw new \RuntimeException('COLMAP did not generate a sparse model in sparse/0. Try a better photo set with more overlap.');
            }

            $this->runProcess([
                $colmap,
                'model_converter',
                '--input_path', $firstModelPath,
                '--output_path', $textOutputPath,
                '--output_type', 'TXT',
            ], $log);

            $pointsTextPath = "{$textOutputPath}/points3D.txt";

            if (! File::exists($pointsTextPath)) {
                throw new \RuntimeException('points3D.txt was not generated by COLMAP model_converter.');
            }

            $payload = $this->parsePointCloud($pointsTextPath);

            Storage::disk($publicDisk)->put(
                $publicOutputPath,
                json_encode($payload, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES)
            );

            $scan->update([
                'status' => 'completed',
                'sparse_model_path' => $firstModelPath,
                'point_cloud_path' => $publicOutputPath,
                'metadata' => array_merge($scan->metadata ?? [], [
                    'points_count' => count($payload['points']),
                    'bounds' => $payload['bounds'],
                ]),
                'processing_log' => implode("\n\n", $log),
                'completed_at' => now(),
            ]);
        } catch (\Throwable $exception) {
            $scan->update([
                'status' => 'failed',
                'error_message' => $exception->getMessage(),
                'processing_log' => implode("\n\n", array_merge($log, [$exception->getMessage()])),
                'completed_at' => now(),
            ]);

            throw $exception;
        }
    }

    private function runProcess(array $command, array &$log): void
    {
        $process = new Process($command, timeout: config('roomscan.command_timeout', 3600));
        $process->run();

        $log[] = implode(' ', array_map('strval', $command)) . "\n" . trim($process->getOutput() . "\n" . $process->getErrorOutput());

        if (! $process->isSuccessful()) {
            throw new \RuntimeException(trim($process->getErrorOutput() ?: $process->getOutput() ?: 'COLMAP command failed.'));
        }
    }

    private function parsePointCloud(string $pointsTextPath): array
    {
        $points = [];
        $maxPoints = (int) config('roomscan.viewer_points_limit', 12000);
        $bounds = [
            'min' => ['x' => null, 'y' => null, 'z' => null],
            'max' => ['x' => null, 'y' => null, 'z' => null],
        ];

        $rawLines = file($pointsTextPath, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES) ?: [];
        $candidateCount = count(array_filter($rawLines, fn ($line) => ! str_starts_with(trim($line), '#')));
        $step = $candidateCount > $maxPoints ? (int) ceil($candidateCount / $maxPoints) : 1;
        $processed = 0;

        foreach ($rawLines as $line) {
            $line = trim($line);

            if ($line === '' || str_starts_with($line, '#')) {
                continue;
            }

            $processed++;

            if ($processed % $step !== 0) {
                continue;
            }

            $parts = preg_split('/\s+/', $line);

            if (! $parts || count($parts) < 7) {
                continue;
            }

            $point = [
                'x' => (float) $parts[1],
                'y' => (float) $parts[2],
                'z' => (float) $parts[3],
                'r' => (int) $parts[4],
                'g' => (int) $parts[5],
                'b' => (int) $parts[6],
            ];

            foreach (['x', 'y', 'z'] as $axis) {
                $bounds['min'][$axis] = $bounds['min'][$axis] === null ? $point[$axis] : min($bounds['min'][$axis], $point[$axis]);
                $bounds['max'][$axis] = $bounds['max'][$axis] === null ? $point[$axis] : max($bounds['max'][$axis], $point[$axis]);
            }

            $points[] = $point;
        }

        return [
            'points' => $points,
            'bounds' => $bounds,
        ];
    }

    private function resolveScanBasePath(string $folder): string
    {
        $candidates = [
            storage_path("app/private/scans/{$folder}"),
            storage_path("app/private/private/scans/{$folder}"),
            Storage::disk('local')->path("scans/{$folder}"),
            Storage::disk('local')->path("private/scans/{$folder}"),
        ];

        foreach ($candidates as $candidate) {
            if (File::isDirectory($candidate) && File::isDirectory($candidate . DIRECTORY_SEPARATOR . 'images')) {
                return $candidate;
            }
        }

        return $candidates[0];
    }
}
